FROM node:alpine
workdir '/home/project'
copy package.json .
run npm install

copy . .

cmd ["npm","run","start"]


#run npm run build

#from nginx
#COPY --from=builder /app/build /usr/share/nginx/html

